# Generated by Django 2.0 on 2020-08-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelloggs_pringles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityList',
            fields=[
                ('prod_name', models.CharField(max_length=145, primary_key=True, serialize=False)),
                ('qnty', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=50)),
            ],
        ),
    ]
