# Generated by Django 2.0 on 2020-08-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelloggs_pringles', '0002_prioritylist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prioritylist',
            old_name='domain',
            new_name='platform',
        ),
        migrations.RenameField(
            model_name='prioritylist',
            old_name='qnty',
            new_name='region',
        ),
        migrations.AddField(
            model_name='prioritylist',
            name='product_id',
            field=models.CharField(default='100470', max_length=75),
            preserve_default=False,
        ),
    ]
