# Generated by Django 2.0 on 2020-08-18 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kelloggs_pringles', '0003_auto_20200818_1319'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriorityList',
        ),
    ]
