# Generated by Django 2.0 on 2020-08-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelloggs_pringles', '0004_delete_prioritylist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fairprice',
            fields=[
                ('item_id', models.CharField(blank=True, max_length=45, null=True)),
                ('name', models.CharField(blank=True, max_length=145, null=True)),
                ('brand', models.CharField(blank=True, max_length=45, null=True)),
                ('quantity', models.CharField(blank=True, max_length=45, null=True)),
                ('price', models.CharField(blank=True, max_length=45, null=True)),
                ('stock', models.CharField(blank=True, max_length=45, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('slnum', models.BigAutoField(primary_key=True, serialize=False)),
                ('stock_status', models.CharField(blank=True, max_length=45, null=True)),
                ('has_priority', models.BooleanField(default=False)),
                ('region', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'fairprice_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shopee',
            fields=[
                ('item_id', models.CharField(blank=True, max_length=45, null=True)),
                ('name', models.CharField(blank=True, max_length=145, null=True)),
                ('brand', models.CharField(blank=True, max_length=45, null=True)),
                ('price', models.CharField(blank=True, max_length=45, null=True)),
                ('stock', models.CharField(blank=True, max_length=45, null=True)),
                ('sold', models.CharField(blank=True, max_length=45, null=True)),
                ('region', models.CharField(blank=True, max_length=45, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('slnum', models.BigAutoField(primary_key=True, serialize=False)),
                ('stock_status', models.CharField(blank=True, max_length=45, null=True)),
                ('has_priority', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'shopee_data',
                'managed': False,
            },
        ),
    ]
