# Generated by Django 2.0 on 2020-08-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MakePriorityList',
            fields=[
                ('prod_name', models.CharField(max_length=145, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
                ('product_id', models.CharField(max_length=75)),
                ('platform', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
            ],
        ),
    ]
